### ISSUE TITLE
master vs main

### ISSUE THREAD

**Issue by JoshuaSBrown** [DavidLeoni/readthedocs-to-actions#4]
Might want to make a note in the documentation that master may not be a branch in the new repos. - It is still set as the default branch.

**Comment by JoshuaSBrown** [comment]
```
          GIT_TAG: master # optional, default is master
```
Might want to add here that main could be the correct branch to use.

**Comment by DavidLeoni** [comment]
Hi Joshua,

Thanks for reporting, to be future-proof I've just released a version v2.0 which defaults to branch 'main'
